blog/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from views import index,show,edit,editAction
urlpatterns = [
    # Examples:
    # url(r'^$', 'boke.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^index/',index ),
    url(r'^show/(?P<id>[0-9]+)',show,name='show'),
    url(r'^edit/(?P<id>[0-9]+)',edit,name='edit'),
    url(r'^editAction/',editAction,name='editAction')
]

boke/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'boke.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^blog/',include('blog.urls',namespace='blog'))
]

blog/models.py
from django.db import models

# Create your models here.

class Article(models.Model):
    title=models.CharField(max_length=32,default='TITLE')
    content=models.TextField(null=True)

    def __unicode__(self):
        return self.title

blog/views.py
from django.shortcuts import render
from models import Article
# Create your views here.

def index(req):
    Arts=Article.objects.all()
    return render(req,'blog/index.html',{'Arts':Arts})

def show(req,id):
    Art=Article.objects.get(pk=id)
    return render(req,'blog/show.html',{'Art':Art})

def edit(req,id):
   if str(id)=='0':
       return render(req,'blog/edit.html')
   Art=Article.objects.get(pk=id)
   return render(req,'blog/edit.html',{'Art':Art})

def editAction(req):
    id=req.POST.get('id')
    tit=req.POST.get('title')
    con=req.POST.get('content')
    if str(id)=='0':
        Article.objects.create(title=tit,content=con)
    else:
        art=Article.objects.get(pk=id)
        art.title=tit
        art.content=con
        art.save()
    arts=Article.objects.all()
    return render(req,'blog/index.html',{'Arts':arts})

templates/blog/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>编辑</title>
</head>
<body>
    <form action="{% url 'blog:editAction'  %}" method="post">
        {% csrf_token %}
        {% if Art %}
            <input type="hidden" value="{{ Art.id }}" name="id">
            <label for="">原文中标题</label>
            <input type="text" value="{{ Art.title }}" name="title">
            <br>
            <label for="">原内容</label>
            <input type="text" value="{{ Art.content }}" name="content">
            <br>
        {% else %}
            <input type="hidden" value="0" name="id">
            <label for="">新建文章标题</label>
            <input type="text" name="title">
            <br>
            <label for="">新建文章内容</label>
            <input type="text" name="content">
            <br>
        {% endif %}
        <input type="submit" value="确定提交">
    </form>
</body>
</html>

templates/blog/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>我的博客主页</title>
</head>
<body>
    <h1>欢迎来到德莱联盟!</h1>
    <br><br>
    {% for Art in Arts %}
        <h1><a href="{% url 'blog:show' Art.id %}">{{ Art.title }}</a></h1>
    {% endfor %}
    <a href="{% url 'blog:edit' 0 %}">发表新文章</a>
</body>
</html>

templates/blog/show.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>{{ Art.title }}</h1>
    <br><br>
    <h3>{{ Art.content }}</h3>
    <br><br>
    <a href="{% url 'blog:edit' Art.id  %}">修改文章</a>
</body>
</html>